[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aria-control"
version = "0.1.0"
description = "A control library for Meta's Project Aria glasses."
authors = [{ name = "Xu Kristen Yan" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "projectaria-tools>=1.5.2a1",
    "projectaria_client_sdk==1.1.0",
    "torch",
    "torchvision",
    "easydict",
    "pyyaml",
    "opencv-python",
    "opencv-contrib-python",
]

[tool.setuptools.packages.find]
where = ["src"]